import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "cyrillic-ext"],
  variable: "--font-inter",
});
import "react-datepicker/dist/react-datepicker.css";

const fixelDisplay = localFont({
  src: [{ path: "../assets/fonts/FixelDisplayRegular.woff2" }],
  display: "swap",
  variable: "--font-fixel-display-mono",
});
const corbel = localFont({
  // I need to add two of the files bold and regular
  src: [
    {
      path: "../assets/fonts/corbel-regular.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/corbel-bold.ttf",
      weight: "700",
    },
  ],
  display: "swap",
  variable: "--font-corbel",
});
const lora = localFont({
  src: [
    { path: "../assets/fonts/Lora-Regular.ttf", weight: "400" },
    {
      path: "../assets/fonts/Lora-Bold.ttf",
      weight: "700",
    },
  ],
  display: "swap",
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${fixelDisplay.variable} ${corbel.variable} ${lora.variable} font-sans`}
      >
        <AppProvider>
          <Toaster
            toastOptions={{
              style: { fontSize: "12px" },
            }}
          />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
